name: "GameVista (Dev)"
services:
  web:
    env_file:
      - .env
      - .env.development
    build:
      context: ./apps/web
    container_name: game-analytics-web-dev
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - API_URL=http://localhost:4000
    volumes:
      - ./apps/web:/app
    command: npm run dev
    depends_on:
      - api

  api:
    env_file:
      - .env
      - .env.development
    build:
      context: ./apps/api
    container_name: game-analytics-api-dev
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:pass@db:5432/analytics
    volumes:
      - ./api:/app
    command: npm run dev
    depends_on:
      - db
