name: "GameVista (Dev)"

networks:
  gamevista_net:
    driver: bridge

services:
  api:
    build:
      context: ./apps/api
      dockerfile: Dockerfile.dev
    container_name: gamevista-api-dev
    networks:
      - gamevista_net
    volumes:
      - ./api:/app
    ports:
      - "4400:4000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://user:pass@db:5432/analytics
    depends_on:
      - db

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile.dev
    container_name: gamevista-web-dev
    networks:
      - gamevista_net
    volumes:
      - ./apps/web:/app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: gamevista-analytics-db
    restart: always
    networks:
      - gamevista_net
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gamevista_analytics
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
