services:
  db:
    image: postgres:15
    container_name: game-analytics-db
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: analytics
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
