name: "gamevista_dev"

networks:
  gamevista_net:
    driver: bridge

services:
  api:
    env_file: .env.development
    build:
      context: ../apps/api
      dockerfile: Dockerfile.dev
    container_name: api
    networks:
      - gamevista_net
    volumes:
      - ./api:/app
    ports:
      - "${API_HOST}:${API_PORT}"
    depends_on:
      - db

  web:
    env_file: .env.development
    build:
      context: ../apps/web
      dockerfile: Dockerfile.dev
    container_name: web
    networks:
      - gamevista_net
    volumes:
      - ./apps/web:/app
    ports:
      - "${WEB_HOST}:${WEB_PORT}"
    depends_on:
      - api

  db:
    image: postgres:15
    container_name: db
    restart: always
    networks:
      - gamevista_net
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: ${GAMEVISTA_DB_USER}
      POSTGRES_PASSWORD: ${GAMEVISTA_DB_PASS}
      POSTGRES_DB: ${GAMEVISTA_DB_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
