name: "GameVista (Prod)"
services:
  web:
    env_file:
      - .env
      - .env.production
    build:
      context: ./apps/web
    container_name: game-analytics-web
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
