name: "gamevista_dev"

networks:
  gamevista_net:
    driver: bridge

services:
  web:
    build:
      context: ../apps/web
      dockerfile: Dockerfile.dev
    container_name: web
    networks:
      - gamevista_net
    volumes:
      - ../apps/web:/app
    ports:
      - "3000:3000"
    env_file: .env.development

  db:
    image: postgres:15
    restart: always
    networks:
      - gamevista_net
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: gamevista_analytics
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    networks:
      - gamevista_net
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json
    depends_on:
      - db

volumes:
  pgdata:
